name: Clone Emojis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  clone_emojis:
    runs-on: ubuntu-latest

    steps:
      - name: Clone microsoft/fluentui-emoji
        uses: actions/checkout@v4
        with:
          repository: microsoft/fluentui-emoji
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          path: emojis/regular

      - name: Clone Tarikul-Islam-Anik/Animated-Fluent-Emojis
        uses: actions/checkout@v4
        with:
          repository: Tarikul-Islam-Anik/Animated-Fluent-Emojis
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          path: emojis/animated

      - uses: actions/checkout@v4
        with:
          path: cdn

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r cdn/fluentui-emoji/scripts/requirements.txt

      - run: tree

      - name: Run clone-emojis.py
        run: python cdn/fluentui-emoji/scripts/clone-emojis.py

      - name: Push to github.com/malte9799/cdn
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions@github.com
          git add cdn/fluentui-emoji/Emojis
          if ! git diff-index --quiet HEAD; then
            git commit -m "Updates"
            git push
          fi
