name: Update Emojis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  clone_emojis:
    runs-on: ubuntu-latest

    steps:
      - name: Clone microsoft/fluentui-emoji
        uses: actions/checkout@v4
        with:
          repository: microsoft/fluentui-emoji
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          path: emojis/regular

      - name: Clone Tarikul-Islam-Anik/Animated-Fluent-Emojis
        uses: actions/checkout@v4
        with:
          repository: Tarikul-Islam-Anik/Animated-Fluent-Emojis
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          path: emojis/animated

      - uses: actions/checkout@v4
        with:
          path: cdn

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: pip install -r cdn/fluentui-emoji/scripts/requirements.txt

      - name: Execute script
        run: python cdn/fluentui-emoji/scripts/clone-emojis.py

      - name: Push changes
        run: |
          cd cdn
          git config user.name github-actions[bot]
          git config user.email github-actions@github.com
          git add fluentui-emoji/Emojis -f
          if ! git diff-index --quiet HEAD; then
            git commit -m "Updates"
            git push
          fi
